import { Provider } from 'react-redux'
import '../styles/globals.scss'
import Head from 'next/head'
import store from './../store';
import Header from './../components/Header/Header';
import Footer from './../components/Footer/Footer';
import Section from './../components/Section/Section';


function MyApp({ Component, pageProps }) {
 return <>
      <Head>
        <title>Diya Interactive App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://diyainteractive.com/wp-content/uploads/2021/03/500x178.png" />
    

      </Head>
 
      <Provider store={store}>
          <Header/>
               <Section>
                    <Component {...pageProps} />
               </Section>
          <Footer />          
      </Provider>
 </>
}

export default MyApp
